### ISSUE TITLE
`Google::Cloud::Storage#download_file` broken when upgrading `google-apis-storage_v1` from version 0.17.0 to 0.19.0

### ISSUE THREAD

**Issue by Florent2** [googleapis/google-cloud-ruby#23403]
#### Environment details

  - OS: MacOS 13.0
  - Ruby version: 2.7.7p221
  - Gem name and version: google-cloud-storage 1.38.0+ and google-apis-storage_v1 0.19.0

#### Code example

```ruby
require "google/cloud/storage"

storage = [Google](https://www.rubydoc.info/gems/google-cloud-storage/1.44.0/Google)::[Cloud](https://www.rubydoc.info/gems/google-cloud-storage/1.44.0/Google/Cloud)::[Storage](https://www.rubydoc.info/gems/google-cloud-storage/1.44.0/Google/Cloud/Storage).[new](https://www.rubydoc.info/gems/google-cloud-storage/1.44.0/Google/Cloud/Storage#new-class_method)

bucket = storage.bucket "my-bucket"

file = bucket.file "path/to/my-file.ext"
file.download "path/to/downloaded/file.ext"
```

#### Full backtrace

```
undefined method `header&#39; for nil:NilClass
.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/google-cloud-storage-1.38.0/lib/google/cloud/storage/file.rb:1049:in `download&#39;
```

`resp` is `nil` in `Google::Cloud::Storage#download_file`.

I can reproduce this error with gem versions 1.38.0 and 1.44 (I've not tried with intermediate versions).

The error does not happen with gem version 1.37.0 and prior.

I think the bug is related with 20dbea689ce46975638c04c57fd81cab9b4f82b4.

**Comment by bajajneha27** [comment]
Hi @Florent2 ,

I tried reproducing this in the latest version of `google-cloud-storage` i.e. `1.47.0` and `1.38.0` , I couldn't reproduce it. Can you please tell me the file extension that you were trying to download?

**Comment by SandeepTuniki** [comment]
@Florent2 Friendly ping!

**Comment by SandeepTuniki** [comment]
I'm closing this issue. If you're still looking for help on this, feel free to re-open with more reproducible info.
