### ISSUE TITLE
undefined method `create_session=' for #<Google::Apis::BigqueryV2::JobConfigurationQuery>

### ISSUE THREAD

**Issue by jeremywadsack** [googleapis/google-cloud-ruby#22471]
When we upgraded `google-cloud-bigquery` to 1.42.0 we started getting errors every time we try to run a query job.

```
undefined method `create_session=' for #<Google::Apis::BigqueryV2::JobConfigurationQuery:0x0000000131cd73c8>
Did you mean?  create_disposition=
```

I rolled back and verified this doesn't fail in 1.37.0 and does in 1.38.0 (which is where `create_session` was introduced). 

`JobConfigurationQuery` is dynamically defined, I believe, and I don't know what's needed to add this support. In any case, it should work without having to make changes.

My suggestions is to change [`query_job.rb` line 799](https://github.com/googleapis/google-cloud-ruby/blob/6a1c74028e38f073b729023815d7d3a4ae982ed7/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L799) to conditionally create the sessions:

```diff
- updater.create_session = options[:create_session]
+ updater.create_session = options[:create_session] if options[:create_session]
```

But I don't understand enough about this to know whether that would still cause problems if you wanted to enable that.

#### Environment details

  - OS: macOS, Ubuntu
  - Ruby version: 2.7.5
  - Gem name and version: google-cloud-bigquery v1.38.0 and later

#### Steps to reproduce

  1. When calling `dataset#query_job` even without a `create_session` it fails with the above error

#### Code example

```ruby
dataset.query_job(query, params: params)
```

#### Full backtrace

```
/home/app/blueprint-ga/vendor/bundle/ruby/2.7.0/gems/google-cloud-bigquery-1.42.0/lib/google/cloud/bigquery/query_job.rb:1056:in `create_session='
/home/app/blueprint-ga/vendor/bundle/ruby/2.7.0/gems/google-cloud-bigquery-1.42.0/lib/google/cloud/bigquery/query_job.rb:800:in `from_options'
/home/app/blueprint-ga/vendor/bundle/ruby/2.7.0/gems/google-cloud-bigquery-1.42.0/lib/google/cloud/bigquery/dataset.rb:1538:in `query_job'
```

**Comment by shivgautam** [comment]
Thank you for filing this issue. The suggestion that you've made does not really fix the issue and only masks it. The actual error appears to be in the create_session method. We'll look into it and update here.

**Comment by diptanshumittal** [comment]
Hi @jeremywadsack,
Thank you for bringing this up. Could you please provide me with more details such as the specific version of the gem `google-apis-bigquery_v2` that you are currently using with `google-cloud-bigquery`.  
You can do so by running `gem list` command from the Gemfile directory.

**Comment by jeremywadsack** [comment]
@diptanshumittal 
```
✗ bundle info google-apis-bigquery_v2
  * google-apis-bigquery_v2 (0.55.0)
	Summary: Simple REST client for BigQuery API V2
	Homepage: https://github.com/google/google-api-ruby-client
	Documentation: https://googleapis.dev/ruby/google-apis-bigquery_v2/v0.55.0
	Source Code: https://github.com/googleapis/google-api-ruby-client/tree/main/generated/google-apis-bigquery_v2
	Changelog: https://github.com/googleapis/google-api-ruby-client/tree/main/generated/google-apis-bigquery_v2/CHANGELOG.md
	Bug Tracker: https://github.com/googleapis/google-api-ruby-client/issues
	Reverse Dependencies: 
		google-cloud-bigquery (1.42.0) depends on google-apis-bigquery_v2 (~> 0.1)
```

**Comment by diptanshumittal** [comment]
Hi @jeremywadsack,
We were unable to reproduce the error locally with version 1.42.0 of `google-cloud-bigquery`. 
Could you please try reinstalling the gems to ensure that the gem files haven't been modified, and then run the script again? Additionally, if there's any other information related to the bug that you can provide, it would be helpful.

**Comment by dazuma** [comment]
The other thing I'd check is whether the `google-api-client` gem is still present in your bundle. If it is, *remove it* because it contains old versions of the bigquery client classes and may be masking the ones from the canonical `google-apis-bigquery_v2` gem.

**Comment by jeremywadsack** [comment]
@dazuma we _do_ have `google-api-client` installed in the bundle. It's a dependency of one of our other gems. We'll upgrade that dependency and I'll follow up and let you know if that resolved it.

**Comment by NivedhaSenthil** [comment]
@jeremywadsack any updates please ? did it resolve the issue ?

**Comment by SandeepTuniki** [comment]
@jeremywadsack Friendly ping. Is this still an issue for you?

**Comment by jeremywadsack** [comment]
@SandeepTuniki I have not had time to update this. I'll go ahead and close this ticket. I'll re-open if there are any issues when we upgrade.
